### ISSUE TITLE
Hacktober Accepted

### ISSUE THREAD

**Issue by rushabhnaik16** [Geeky-star/Footer-and-Header-design-Challenge#10]
I have created another pull request to add a header design. Please add the Hacktober Accepted label to it.
Thank you!

**Comment by Geeky-star** [comment]
I have added the label. I hope its showing hacktoberfest-accepted repository now.

**Comment by rushabhnaik16** [comment]
> 
> 
> I have added the label. I hope its showing hacktoberfest-accepted repository now.

Yes its showing..Thank you!
