### ISSUE TITLE
Not Hacktoberfest accepted

### ISSUE THREAD

**Issue by lapohjan** [Geeky-star/Footer-and-Header-design-Challenge#13]
Hi. I just contributed with my footer design but the pull request wasn't accepted by Hacktoberfest. Is it possible to fix this? Thanks!

**Comment by Geeky-star** [comment]
> Hi. I just contributed with my footer design but the pull request wasn't accepted by Hacktoberfest. Is it possible to fix this? Thanks!

Don't worry it will show hacktoberfest accepted when I label it.
