### ISSUE TITLE
Not a hacktober fest accept repo

### ISSUE THREAD

**Issue by rushabhnaik16** [Geeky-star/Footer-and-Header-design-Challenge#8]
In my hacktober fest dashboard it's telling this isn't an  repo for the fest but you had added a tag saying is this hacktober-accepted. Please check this out once.

**Comment by Geeky-star** [comment]
> In my hacktober fest dashboard it's telling this isn't an repo for the fest but you had added a tag saying is this hacktober-accepted. Please check this out once.

I hope it is now showing hacktoberfest accepted. I have labelled it.

**Comment by rushabhnaik16** [comment]
Yes it is showing the label now...thank you!
